spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:ORCL
    username: hr
    password: hr

server:
  port: 8888
  context-path: /spring-boot
  jsp-servlet:
    init-parameters:
      development: true